# Generated by Django 4.0.2 on 2022-04-12 19:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='article',
        ),
        migrations.RenameField(
            model_name='inlinecomment',
            old_name='post',
            new_name='article',
        ),
        migrations.AlterField(
            model_name='comment',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('c10dcd54-f552-4842-95ff-c9624a44b54f'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='inlinecomment',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('c10dcd54-f552-4842-95ff-c9624a44b54f'), primary_key=True, serialize=False),
        ),
    ]
