# Generated by Django 4.0.2 on 2022-07-17 19:47

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_comment_frozen_comment_thread_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='uid',
            field=django_extensions.db.fields.ShortUUIDField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='inlinecomment',
            name='uid',
            field=django_extensions.db.fields.ShortUUIDField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
