# Generated by Django 4.0.2 on 2022-05-24 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='uuid',
            new_name='id',
        ),
    ]
