# Generated by Django 4.0.2 on 2022-05-24 10:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='inlinecomment',
            name='uuid',
        ),
        migrations.AddField(
            model_name='comment',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7b386bf6-62c7-4512-be32-2862c0b2b944'), primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='inlinecomment',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7b386bf6-62c7-4512-be32-2862c0b2b944'), primary_key=True, serialize=False),
        ),
    ]
